### ISSUE TITLE
✨ feat: 음악 미리듣기 재생 페이지 및 Playbar 기능 구현 및 마크업  

### ISSUE THREAD

**Issue by ony540** [FESP-8/PixelBeat#12]
# 요약
음악 미리듣기 재생 페이지 및 Playbar 기능 구현 및 마크업을 한다.

# Todo
- [x] Playbar 마크업
- [x] /playnow 페이지 마크업
- [x] 비로그인 유저의 음악 영수증 페이지에서 재생 버튼을 누르면 Playbar와 함께 미리듣기 재생기능 구현
- [x] /playnow 에서도 재생기능 유지 (음악 재생상태와 재생목록을 zustand store에 저장한다)

# ETC
기타사항
