### ISSUE TITLE
✨ feat: 추천 로직 수정 및 Bill database 연결

### ISSUE THREAD

**Issue by ony540** [FESP-8/PixelBeat#19]
# 요약
추천 로직 수정 및 Bill database 연결한다. 

# Todo
- [x] 추천 로직을 useQuery를 사용하여 로직을 수정한다.
- [x] 그려지는 그래프의 데이터를 추천받은 음악 8개 기준으로 계산한다.
- [x] BillPage로 넘어갈때 supabase에 bill을 업로드한다.

# ETC
