### ISSUE TITLE
♻️ refactor: 로그인 및 회원가입 컴포넌트 수정

### ISSUE THREAD

**Issue by dotory0829** [FESP-8/PixelBeat#29]
# 요약
로그인, 회원가입, 프로필 설정 기존 코드 수정 ( 추후 더 수정 필요함 )

# Todo
- [x] 기존 loginBtn, emilBtn 아이콘 PixelBeatLoginButton,SpotifyLoginButton로 이름 변경 후 내부 디테일 수정 (폰트 SVG 삭제 후 텍스트 추가)
- [x] 기존 이메일 로그인, 회원가입 컴포넌트 명 ~ 내부 로직 전부 수정
- [x] 기존 컴포넌트 명: `SignUpEmail`
- [x] `Sign(in, up)WithEmail.tsx` 로 변경
- [x] SVG 아이콘 rule 속성 카멜케이스로 변경 
- [x] 기존 signupForm에 있던 메세지 로직 ValidationErrorMessage 컴포넌트로 따로 분리 등
