### ISSUE TITLE
✨ feat: home에서 미리듣기 기능 구현 및 배너 마크업

### ISSUE THREAD

**Issue by ony540** [FESP-8/PixelBeat#31]
# 요약
home에서 미리듣기 기능 구현 및 배너 마크업

# Todo
- [x] api 파일구조 분리
- [x] home에서 미리듣기 기능 구현
- [x] home의 배너 추가 작업

# ETC
기타사항
