### ISSUE TITLE
✨ feat: search, album, artist 페이지 기능 추가 및 스타일 수정

### ISSUE THREAD

**Issue by ony540** [FESP-8/PixelBeat#38]
# 요약
search, album, artist 페이지  기능 추가 및 스타일 수정

# Todo
- [x] search 페이지 처음 접근 시 인풋 포커스 되도록하기
- [x] search 검색결과에 플레이리스트 추가하기
- [x] album, artist 페이지에 재생 기능 추가 및 스타일 수정

# ETC
기타사항
