### ISSUE TITLE
🎨 style:  음악추천 리스트 마크업 및 기능 구현

### ISSUE THREAD

**Issue by LKJ970524** [FESP-8/PixelBeat#4]
# 요약
영수증 페이지 마크업 및 기능 구현

# Todo
- [x]  처음 비로그인 유저가 추천받는 영수증 페이지를 마크업한다.
- [x] assets 파일 추가한다.
- [x] chart.js를 설치해 그래프를 구현한다.
- [x] 공유 기능을 구현한다. 

# ETC
기타사항
