### ISSUE TITLE
✨ feat: 로그인 시 사용자 정보 db 접근하여 zustand에 저장하기

### ISSUE THREAD

**Issue by ony540** [FESP-8/PixelBeat#45]
# 요약
로그인 시 사용자 정보 db 접근하여 zustand에 저장하기

# Todo
- [x] 회원가입 완료 후 home에 왔을때 zustand에 저장된 bill이 있으면 해당 billDB에 owner를 업데이트
- [ ] 유저가 premium 유저인지 아닌지 확인하여 db update 
- [x] 로그인 시 사용자 정보 db 접근하여 zustand에 저장하기

# ETC
기타사항
