### ISSUE TITLE
✨ feat: 서치, 앨범, 가수 페이지의 재생 기능 구현 

### ISSUE THREAD

**Issue by ony540** [FESP-8/PixelBeat#54]
# 요약
서치, 앨범, 가수 페이지의 재생 기능 구현 및 confirm 컴포넌트 사용하기

# Todo
- [x] 서치, 페이지의 재생 기능 구현 
- [x] 앨범, 가수 페이지의 재생 기능 구현 
- [x] Confirm 컴포넌트 사용

# ETC
기타사항
